CREATE TABLE projects
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    name            VARCHAR(255)                                NOT NULL,
    description     TEXT,
    owner_id        BIGINT                                      NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_projects_owner ON projects(owner_id);