CREATE TABLE tasks(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    title       VARCHAR(255)                                NOT NULL,
    description TEXT,
    status      VARCHAR(50)                                NOT NULL,
    priority    VARCHAR(50)                                NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deadline    DATE,
    owner_id    BIGINT                                      NOT NULL,
    project_id  BIGINT                                      NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_on_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_tasks_on_project FOREIGN KEY (project_id) REFERENCES projects (id) on DELETE CASCADE
);


CREATE INDEX idx_tasks_owner_project ON tasks(owner_id, project_id);